import { Competition } from "./types";

export const competitionsData: Competition[] = [
  {
    id: "recoil",
    title: "RECOIL",
    category: "Esports & Gaming",
    iconName: "Gamepad2",
    description: "The premier high-stakes tactical shooter arena. Face off against elite regional school squads in standard five-versus-five tactical combat, testing mechanical precision, team coordination, and split-second strategic executes.",
    rules: [
      "Valorant [Riot Games] would be the game played in the competition.",
      "Only one team can participate from each school and each team must consist of 6 members (5 core + 1 substitute).",
      "Each game will be played according to the standard rules of the game.",
      "The brackets for the tournament will be revealed on the day of the event itself.",
      "Any inappropriate behavior (including abusive language, teasing, etc.) will lead to disqualification.",
      "Players can carry their own peripherals (keyboards, mouse, mic, headphones, etc.).",
      "The matches will be played on the PCs provided by the school.",
      "The players must log in with their respective Riot accounts on the PCs.",
      "If any suspicious gameplay is observed, it will be reviewed and might lead to disqualification."
    ],
    teamSize: "6 Members (5 Core + 1 Sub)",
    eligibility: "Classes IX-XII",
    selectionMethod: "Live school tryout custom lobbies evaluating aim precision, communications, and mechanical play.",
    coordinators: ["Mr. Joseph Peter (HOD Computer Science)", "Adithya Vardhan (XII, Tech President)"],
    pastelBg: "bg-indigo-950/20",
    pastelBorder: "border-indigo-500/20",
    pastelAccent: "text-indigo-400 bg-indigo-950/30 border-indigo-500/20",
    glowColor: "shadow-sm"
  },
  {
    id: "encode",
    title: "ENCODE",
    category: "Competitive Programming",
    iconName: "Terminal",
    description: "The ultimate algorithmic sprint. Construct highly optimized Python solutions to complex logic gates, data streams, and graphical interface statements in a dual-round timed battle.",
    rules: [
      "Python will be the programming language tested.",
      "Only one team can participate from each school.",
      "The participating team must consist of two members.",
      "This competition will consist of two rounds.",
      "The total duration of the event is 130 minutes (60 minutes for each round + 10 minutes relaxation time).",
      "The first round is designed to test the programming fundamentals and graphical skills of the participants.",
      "During the second round, participants will have to solve logical problem statements with the help of Python code.",
      "Any pre-written code or program is strictly prohibited and can lead to immediate disqualification.",
      "Only IDLE Editor shall be used for programming.",
      "Participants should be well equipped with the knowledge of file handling/Python connectivity/graphical module (PyGame module)."
    ],
    teamSize: "1 Team (2 Members)",
    eligibility: "Classes VIII-XII",
    selectionMethod: "90-minute Python coding screening covering algorithms, PyGame layouts, and data connectivity.",
    coordinators: ["Mr. Rajesh K. (Senior IT Faculty)", "Sanya Sen (XII, Coding Lead)"],
    pastelBg: "bg-emerald-950/20",
    pastelBorder: "border-emerald-500/20",
    pastelAccent: "text-emerald-400 bg-emerald-950/30 border-emerald-500/20",
    glowColor: "shadow-sm"
  },
  {
    id: "qurious",
    title: "QURIOUS",
    category: "Trivia & Tech History",
    iconName: "HelpCircle",
    description: "A high-octane quiz arena probing the depths of computer history, tech giants, obscure internet lore, hardware architecture, and futuristic digital trends.",
    rules: [
      "Qurious is a quizzing event which shall test the technological aptitude of the participants and their knowledge in the field of Information Technology.",
      "Only one team can participate from each school.",
      "The participating team must consist of two members.",
      "The competition will consist of two rounds (Preliminary + Stage round).",
      "The preliminary round will be a pen-paper round.",
      "The top 5 teams in the preliminary round will advance to the stage round.",
      "The format of the stage round will be disclosed on the day of the symposium itself.",
      "The use of any device or software is strictly prohibited and can lead to immediate disqualification.",
      "Any misbehavior (abuse, slang language, teasing, etc.) will lead to immediate disqualification."
    ],
    teamSize: "1 Team (2 Members)",
    eligibility: "Classes VI-XII",
    selectionMethod: "A 50-question diagnostic tech trivia worksheet evaluating quick retrieval and tech history depth.",
    coordinators: ["Mrs. Sarah George (Dept. of IT)", "Aravind Nair (XI, Quizzing Captain)"],
    pastelBg: "bg-amber-950/20",
    pastelBorder: "border-amber-500/20",
    pastelAccent: "text-amber-400 bg-amber-950/30 border-amber-500/20",
    glowColor: "shadow-sm"
  },
  {
    id: "monochrome",
    title: "MONOCHROME",
    category: "Photography",
    iconName: "Camera",
    description: "An evocative visual hunt capturing depth, light contrast, and architectural geometry under a strict black-and-white constraint.",
    rules: [
      "Monochrome is not a team-based event.",
      "Only a single student can participate from each school.",
      "The topic will be revealed just before the commencement of the competition.",
      "Participants shall carry their own cameras and any other required accessories (tripod, monopod, lenses, etc.).",
      "The total time allotted for taking pictures will be 90 minutes.",
      "The participants can submit only one final photograph.",
      "Use of mobile phones for photography is strictly prohibited.",
      "Participants also need to submit an EXIF (Exchangeable image file format) file of their submission."
    ],
    teamSize: "1 Representative",
    eligibility: "Classes VIII-XII",
    selectionMethod: "Submission of three raw black-and-white compositions demonstrating exposure balance and technical EXIF accuracy.",
    coordinators: ["Mrs. Nalini Sharma (Dept. of Fine Arts)", "Diya Sen (XII, Media President)"],
    pastelBg: "bg-slate-900/20",
    pastelBorder: "border-slate-500/20",
    pastelAccent: "text-slate-300 bg-slate-900/30 border-slate-500/20",
    glowColor: "shadow-sm"
  },
  {
    id: "pixel-perfect",
    title: "PIXEL PERFECT",
    category: "UI/UX & Graphic Design",
    iconName: "Palette",
    description: "A fast-paced digital graphic and layout sprint. Synthesize professional color palettes, crisp grids, and elegant typography hierarchies to build an impactful thematic poster.",
    rules: [
      "The participants are required to create a poster on a given topic.",
      "Adobe Photoshop and GIMP will be installed on the provided PCs.",
      "Internet access will be provided.",
      "The poster should be submitted in A4 (2480x3508px) size.",
      "The image file of the poster (JPG/PNG) shall be submitted along with the native raw file.",
      "The total time allotted for finishing the design is 90 minutes.",
      "Judging Criteria: Color Scheme, Typography, Element Positioning, Alignment and Sequencing, Visual Appeal."
    ],
    teamSize: "1 Representative",
    eligibility: "Classes VIII-XII",
    selectionMethod: "60-minute typography pairing and alignment challenge evaluating raw poster-making techniques.",
    coordinators: ["Mrs. Nalini Sharma (Dept. of Fine Arts)", "Meera Nair (XI, Design Club Head)"],
    pastelBg: "bg-rose-950/20",
    pastelBorder: "border-rose-500/20",
    pastelAccent: "text-rose-400 bg-rose-950/30 border-rose-500/20",
    glowColor: "shadow-sm"
  },
  {
    id: "kinetiq",
    title: "KINETIQ",
    category: "Artificial Intelligence",
    iconName: "Brain",
    description: "Build, train, and demonstrate. Present a fully functional, custom-trained machine learning prototype responding to crucial real-world problem statements.",
    rules: [
      "Participants are required to present a functional AI model based on a real-world problem statement.",
      "The model should be developed using any AI/ML framework such as TensorFlow, PyTorch, or scikit-learn.",
      "Internet access will not be provided during the event.",
      "Participants must bring their own laptops and pre-trained models.",
      "Time allotted for setup and presentation is 15 minutes per team.",
      "Each team must explain the architecture, dataset used, evaluation metrics, and deployment strategy of the model.",
      "Judging Criteria: Innovation and Relevance, Technical Implementation, Presentation Clarity, Model Performance, Feasibility and Scalability"
    ],
    teamSize: "1 Team (1-2 Members)",
    eligibility: "Classes XI-XII",
    selectionMethod: "A proposal paper review detailing problem formulation, model training loss convergence, and validation score.",
    coordinators: ["Mr. Joseph Peter (HOD Computer Science)", "Pranav Arya (XII, Tech Lead)"],
    pastelBg: "bg-fuchsia-950/20",
    pastelBorder: "border-fuchsia-500/20",
    pastelAccent: "text-fuchsia-400 bg-fuchsia-950/30 border-fuchsia-500/20",
    glowColor: "shadow-sm"
  },
  {
    id: "cinephila",
    title: "CINEPHILA",
    category: "Filmmaking & Editing",
    iconName: "Film",
    description: "A grueling 3-hour local filming and editing challenge. Compose, sequence, and color-grade a compelling cinematic narrative matching a live theme.",
    rules: [
      "The participants are required to create a short film on the given topic.",
      "Adobe Premiere Pro, DaVinci Resolve, and Filmora Video Editor will be installed on the provided PCs.",
      "Internet access will not be provided.",
      "The film should be submitted in the aspect ratio 16:9 (1920x1080p).",
      "The total time allotted for shooting and editing the film is 3 hours.",
      "The participants are supposed to bring their own equipment (cameras, tripods, etc.).",
      "The native file of the edited film is also required to be submitted.",
      "Judging Criteria: Cinematography, Colour Grading, Footage Quality, Direction, Story"
    ],
    teamSize: "1 Team (1-3 Members)",
    eligibility: "Classes IX-XII",
    selectionMethod: "Cinematographic portfolio review or a 2-minute raw short film segment review evaluating sequencing and pacing.",
    coordinators: ["Mrs. Nalini Sharma (Dept. of Fine Arts)", "Diya Sen (XII, Media President)"],
    pastelBg: "bg-cyan-950/20",
    pastelBorder: "border-cyan-500/20",
    pastelAccent: "text-cyan-400 bg-cyan-950/30 border-cyan-500/20",
    glowColor: "shadow-sm"
  }
];
